### PR TITLE
Get status current users saved track status

### PR DESCRIPTION
**Pull request by kimipsen**
Gets the status of the list of tracks on the current users saved tracks playlist.

### CODE REVIEW

**Comment by Domochip** [comment]
Hi,

I can't find this api in the Player Section (https://developer.spotify.com/documentation/web-api/reference/#/operations/get-information-about-the-users-current-playback)
Where did you find it?
What is $Id parameter (no description)

thanks

**Comment by wardbox** [comment]
Could we house this under the `Tracks` folder since the method falls under that in their documentation?

**Comment by kimipsen** [comment]
Sure, not a big deal. I just placed it under `Player` because of the `me`-part in the url.

**Comment by Domochip** [comment]
What's your mind about naming this function : **Test-UserSavedTrack** ?
Powershell approved equivalent verb of "Check"(verify) would be "Test".

Regarding description of the function: **Check if one or more tracks is already saved in the current Spotify user's 'Your Music' library.**
Which is the one in the official doc : https://developer.spotify.com/documentation/web-api/reference/#/operations/check-users-saved-tracks

**Comment by kimipsen** [comment]
I have no preference for either, so renaming would be fine for me.

**Review by Domochip — APPROVED** [review]

**Pull request merged**
